
services:
  db:
    image: mysql:8
    restart: unless-stopped
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  wordpress:
    image: wordpress:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    expose:
      - "80"
    volumes:
      - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      # Cannot make it work with /etc/hosts, it needs https://nip.io/
      #VIRTUAL_HOST: wordpress.192.168.1.101.nip.io
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - wordpress
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data:
  wp_data:
