---
- hosts: gunicorn
  vars:
  - JAR_DEST_PATH: /home/chrichri/helloworld-0.0.1-SNAPSHOT.jar
  become: yes
  tasks:
  - name: Install Java 17
    apt:
      name: openjdk-17-jdk
      state: present

  - name: Copy Spring Boot Application
    copy:
      src: /home/chrichri/Documents/Campus-St-Michel-IT/production-deployment/helloworld/build/libs/helloworld-0.0.1-SNAPSHOT.jar
      dest: "{{ JAR_DEST_PATH }}"

  - name: Run Spring Boot Application
    shell: nohup java -jar {{ JAR_DEST_PATH }} &